
default_platform(:android)

platform :android do
  desc "Lane for android app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor Production --target lib/main_Production.dart"
  firebase_app_distribution(
      app: "1:146226765185:android:bb926db4aea35de8f15c80",
      firebase_cli_token:ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "abdelrahmantemsah30@gmail.com",
      release_notes:"First Fastlane Firbase Distribution "
    )

  end
end
